name: url_builder
version: 1.0.0
description: Provides UrlBuilder functions.
repository: https://github.com/onepub-dev/url_builder
environment: 
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies: 
  lint_hard: ^2.0.0
  test: ^1.16.0
